# Generated by Django 3.2.4 on 2021-10-25 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discord', '0002_auto_20211025_1054'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='profile',
        ),
        migrations.AddField(
            model_name='message',
            name='key',
            field=models.CharField(default='asdf', max_length=256),
            preserve_default=False,
        ),
    ]
